import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Omar
 */
public class frmBuscar extends javax.swing.JFrame {
    Connection con;           
    PreparedStatement psmt;
    ResultSet rs;
    DefaultTableModel model;

    /**
     * Creates new form frmBuscar
     */
    public frmBuscar() {
        model = new DefaultTableModel(null, getColumnasBusqueda());
        initComponents();
    }
    
    public String[] getColumnasBusqueda(){
        return new String[] {"Titulo", "Descripción", "Cluster"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barraBuscar = new javax.swing.JTextField();
        label_Buscar = new javax.swing.JLabel();
        combo_Selector = new javax.swing.JComboBox<String>();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        btn_VerOferta = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        //jButton1 = new javax.swing.JButton();
        label_Buscar1 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Utsaah", 0, 29)); // NOI18N
        jLabel6.setText("LA CULTURA");

        jLabel5.setFont(new java.awt.Font("Utsaah", 1, 30)); // NOI18N
        jLabel5.setText("VIVE");

        jLabel9.setFont(new java.awt.Font("Utsaah", 0, 29)); // NOI18N
        jLabel9.setText("EMPRENDEDORA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoOTT.jpg"))); // NOI18N
        jLabel3.setText("jLabel1");

        barraBuscar.setToolTipText("Buscar...");

        label_Buscar.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        label_Buscar.setText("Buscar");

        combo_Selector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Investigador", "Oferta", "Cluster" }));
        combo_Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_SelectorActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tablaResultados.setModel(model);
        jScrollPane1.setViewportView(tablaResultados);

        btn_VerOferta.setText("Ver oferta");
        btn_VerOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerOfertaActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        label_Buscar1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        label_Buscar1.setText("Cluster");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_VerOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_Buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_Buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(barraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_VerOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Buscar)
                            .addComponent(label_Buscar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_Selector)
                            .addComponent(barraBuscar)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VerOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerOfertaActionPerformed
        System.out.println(tablaResultados.getSelectedRow());
        if(tablaResultados.getSelectedRowCount() > 0){
            try{
                Connection con = conexion.getConexion();
                String query = "";
                String Antecedente = "", Ventajas = "", Mercado = "", clave = "", 
                        estatus_pat = "", est_desarrollo = "";
                
                String titulo = model.getValueAt(tablaResultados.getSelectedRow(), 0).toString();
                String descripcion = model.getValueAt(tablaResultados.getSelectedRow(), 1).toString();
                String cluster = model.getValueAt(tablaResultados.getSelectedRow(), 2).toString();

                query = "SELECT Antecedente, Ventajas, Mercado FROM oferta WHERE titulo like '" + titulo
                        + "' ";

                System.out.println(query);
                psmt = con.prepareStatement(query);
                rs = psmt.executeQuery(query);
                
                while (rs.next()){
                    Antecedente = rs.getString("Antecedente");
                    Ventajas = rs.getString("Ventajas");
                    Mercado = rs.getString("Mercado");
                    
                }
                fromVerOferta fr = new fromVerOferta();
                fr.setTitles(titulo, Antecedente, descripcion, Ventajas, Mercado, clave, estatus_pat, est_desarrollo);
                fr.setVisible(true);
                con.close();
            }catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        }
        else{
            JOptionPane.showMessageDialog(null,"Seleccione un resultado");
        }
    }//GEN-LAST:event_btn_VerOfertaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // Borrar elementos de la tabla
        model.getDataVector().removeAllElements();
        
        // Regresar el selector activo
        String selector = (String)combo_Selector.getSelectedItem();
        String query = "";
        Object datos[] = new Object[3];
        
        try{
            Connection con = conexion.getConexion();
            if(selector == "Investigador"){
                query = "SELECT titulo, Descripcion, c.nombre FROM cluster c "
                        + "JOIN oferta o ON o.Cluster_idCluster = c.idCluster "
                        + "JOIN oferta_investigador oi ON oi.idOferta = o.idOferta "
                        + "JOIN investigador i ON i.idInvestigador = oi.idInvestigador "
                        + "WHERE i.nombre LIKE trim('" + barraBuscar.getText()+"')";
            } else if (selector == "Oferta"){
                query = "SELECT titulo, Descripcion, nombre "
                        + "FROM cluster c JOIN oferta o "
                        + "ON o.Cluster_idCluster = c.idCluster "
                        + "WHERE titulo LIKE trim('" + barraBuscar.getText()+"')";
            } else if (selector == "Cluster"){
                query = "SELECT titulo, Descripcion, nombre "
                        + "FROM cluster c JOIN oferta o "
                        + "ON o.Cluster_idCluster = c.idCluster "
                        + "WHERE c.nombre LIKE trim('" + barraBuscar.getText()+"')";
            }
            
            // Preparar consulta y recibir resultados
            psmt = con.prepareStatement(query);
            rs = psmt.executeQuery(query);
            
            // Agregar resultados al modelo
            while(rs.next()){
                for (int i = 0; i < 3; i++){
                    datos[i] = rs.getObject(i + 1);
                }
                model.addRow(datos);
            }
            
            con.close();
        }catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void combo_SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_SelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_SelectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btn_VerOferta;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JComboBox<String> combo_Selector;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Buscar;
    private javax.swing.JLabel label_Buscar1;
    private javax.swing.JTable tablaResultados;
    // End of variables declaration//GEN-END:variables
}
