/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Omar
 */
public class fromVerOferta extends javax.swing.JFrame {
    /**
     * Creates new form fromVerOferta
     */
    public fromVerOferta() {
        initComponents();
    }
    public void setTitles(String titulo, String Antecedente, String Descripcion,
            String ventajas, String mercado, String patente, String estatus_pat, String est_desarrollo) {
        label_titulo.setText(titulo);
        area_descripcion.setText(Descripcion);
        area_antecedente.setText(Antecedente);
        area_ventajas.setText(ventajas);
        field_mercado.setText(mercado);
        field_patente.setText(patente + " - " + estatus_pat);
        field_estatus.setText(est_desarrollo);
        
        // Populate all other fields
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_titulo = new javax.swing.JLabel();
        label_descripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_descripcion = new javax.swing.JTextArea();
        label_antecedente = new javax.swing.JLabel();
        label_ventajas = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        area_ventajas = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_antecedente = new javax.swing.JTextArea();
        label_mercado = new javax.swing.JLabel();
        field_mercado = new javax.swing.JTextField();
        label_detalles1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label_Patente = new javax.swing.JLabel();
        field_patente = new javax.swing.JTextField();
        label_estatus = new javax.swing.JLabel();
        field_estatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_titulo.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N

        label_descripcion.setText("Descripción");

        area_descripcion.setColumns(20);
        area_descripcion.setRows(5);
        jScrollPane2.setViewportView(area_descripcion);

        label_antecedente.setText("Antecedente");

        label_ventajas.setText("Ventajas");

        area_ventajas.setColumns(20);
        area_ventajas.setRows(5);
        jScrollPane3.setViewportView(area_ventajas);

        area_antecedente.setColumns(20);
        area_antecedente.setRows(5);
        jScrollPane1.setViewportView(area_antecedente);

        label_mercado.setText("Mercado");

        field_mercado.setToolTipText("");
        field_mercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_mercadoActionPerformed(evt);
            }
        });

        label_detalles1.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        label_detalles1.setText("Detalles:");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label_Patente.setText("Patente");

        label_estatus.setText("Estatus");

        field_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_estatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(field_mercado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_detalles1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_descripcion)
                            .addComponent(label_antecedente)
                            .addComponent(label_ventajas)
                            .addComponent(label_mercado)
                            .addComponent(label_Patente)
                            .addComponent(label_estatus))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(field_estatus)
                    .addComponent(field_patente))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_detalles1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_antecedente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_ventajas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_mercado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_mercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Patente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_patente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_estatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_mercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_mercadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_mercadoActionPerformed

    private void field_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_estatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromVerOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromVerOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromVerOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromVerOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromVerOferta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_antecedente;
    private javax.swing.JTextArea area_descripcion;
    private javax.swing.JTextArea area_ventajas;
    private javax.swing.JTextField field_estatus;
    private javax.swing.JTextField field_mercado;
    private javax.swing.JTextField field_patente;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_Patente;
    private javax.swing.JLabel label_antecedente;
    private javax.swing.JLabel label_descripcion;
    private javax.swing.JLabel label_detalles1;
    private javax.swing.JLabel label_estatus;
    private javax.swing.JLabel label_mercado;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_ventajas;
    // End of variables declaration//GEN-END:variables
}
